import ast
import importlib.resources
from pathlib import Path

import typer

from piping_bag.config import (
    QUERIES_DIR,
    SCHEMA_PATH,
    PipingBagConfig,
    parse_database_url,
)
from piping_bag.runner import run

app = typer.Typer(help="piping_bag — pgschema + SQLC unified CLI")


def _load_config() -> tuple[PipingBagConfig, dict[str, str]]:
    config = PipingBagConfig()  # type: ignore[call-arg]
    pg_env = parse_database_url(config.database_url)
    return config, pg_env


def _read_template(name: str) -> str:
    templates = importlib.resources.files("piping_bag") / "templates"
    return (templates / name).read_text(encoding="utf-8")


@app.command()
def init() -> None:
    """Scaffold a new piping_bag project (db/schema.sql, db/queries/, sqlc.yaml, .env)."""
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    QUERIES_DIR.mkdir(parents=True, exist_ok=True)

    files: dict[Path, str] = {
        SCHEMA_PATH: _read_template("schema.sql"),
        QUERIES_DIR / "example.sql": _read_template("example.sql"),
        Path("sqlc.yaml"): _read_template("sqlc.yaml"),
    }

    for path, content in files.items():
        if path.exists():
            typer.echo(f"  exists  {path}")
        else:
            path.write_text(content, encoding="utf-8")
            typer.echo(f"  create  {path}")

    env_path = Path(".env")
    if not env_path.exists():
        env_path.write_text(
            'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/mydb"\n',
            encoding="utf-8",
        )
        typer.echo(f"  create  {env_path}")
    else:
        typer.echo(f"  exists  {env_path}")

    typer.echo("\nDone! Edit .env with your DATABASE_URL, then run: pb up")


@app.command()
def dump() -> None:
    """Dump current database schema to db/schema.sql."""
    _, pg_env = _load_config()
    run(["pgschema", "dump", "--file", str(SCHEMA_PATH)], env=pg_env)


@app.command()
def plan() -> None:
    """Plan migration (diff desired schema vs live database)."""
    _, pg_env = _load_config()
    run(["pgschema", "plan", "--file", str(SCHEMA_PATH)], env=pg_env)


@app.command()
def apply() -> None:
    """Apply planned migration to the database."""
    _, pg_env = _load_config()
    run(["pgschema", "apply", "--file", str(SCHEMA_PATH)], env=pg_env)


@app.command()
def sync() -> None:
    """Plan and apply migration in one step."""
    _, pg_env = _load_config()
    run(["pgschema", "plan", "--file", str(SCHEMA_PATH)], env=pg_env)
    run(["pgschema", "apply", "--file", str(SCHEMA_PATH)], env=pg_env)


def _is_query_class(node: ast.ClassDef) -> bool:
    """Check if an AST class node is a sqlc query class (has __slots__ = ("_conn",))."""
    for item in node.body:
        if (
            isinstance(item, ast.Assign)
            and any(
                isinstance(t, ast.Name) and t.id == "__slots__"
                for t in item.targets
            )
            and isinstance(item.value, ast.Tuple)
            and any(
                isinstance(elt, ast.Constant) and elt.value == "_conn"
                for elt in item.value.elts
            )
        ):
            return True
    return False


def _extract_query_class_names(source: str) -> list[str]:
    """Extract top-level query class names (classes with __slots__ = ("_conn",))."""
    tree = ast.parse(source)
    return [
        node.name
        for node in ast.iter_child_nodes(tree)
        if isinstance(node, ast.ClassDef) and _is_query_class(node)
    ]


def _discover_generated_classes(generated_dir: Path) -> list[tuple[str, str]]:
    """Scan generated_dir for modules with query classes. Returns (module_name, class_name) pairs."""
    skip = {"__init__.py", "models.py"}
    results: list[tuple[str, str]] = []
    for py_file in sorted(generated_dir.glob("*.py")):
        if py_file.name in skip:
            continue
        source = py_file.read_text(encoding="utf-8")
        for class_name in _extract_query_class_names(source):
            results.append((py_file.stem, class_name))
    return results


def _generate_db_init(classes: list[tuple[str, str]]) -> str:
    """Generate the content of db/__init__.py with a unified Queries facade."""
    lines: list[str] = [
        "# Auto-generated by piping_bag. Do not edit.",
        "from typing import Annotated, AsyncGenerator",
        "",
        "from fastapi import Depends",
        "from piping_bag.fastapi import get_pool",
        "",
    ]

    # Imports
    for module, cls in classes:
        lines.append(f"from db.generated.{module} import {cls}")
    lines.append("")
    lines.append("")

    # Queries class
    attrs = [(cls[0].lower() + cls[1:], cls) for _, cls in classes]

    lines.append("class Queries:")
    lines.append("    def __init__(self, conn):")
    lines.append("        self._conn = conn")
    for attr, cls in attrs:
        lines.append(f"        self._{attr} = {cls}(conn)")
    lines.append("")

    # __getattr__
    delegate_tuple = ", ".join(f"self._{attr}" for attr, _ in attrs)
    lines.append("    def __getattr__(self, name):")
    lines.append(f"        for delegate in ({delegate_tuple},):")
    lines.append("            if hasattr(type(delegate), name):")
    lines.append("                return getattr(delegate, name)")
    lines.append("        raise AttributeError(f\"Queries has no attribute {name!r}\")")
    lines.append("")
    lines.append("")

    # Dependency
    lines.append("async def _get_queries() -> AsyncGenerator[Queries]:")
    lines.append("    pool = get_pool()")
    lines.append("    async with pool.acquire() as conn:")
    lines.append("        yield Queries(conn)")
    lines.append("")
    lines.append("")
    lines.append("QueriesDep = Annotated[Queries, Depends(_get_queries)]")
    lines.append("")

    return "\n".join(lines)


def _write_db_init() -> None:
    """Write db/__init__.py with a unified Queries facade after SQLC generation."""
    generated_dir = Path("db/generated")
    classes = _discover_generated_classes(generated_dir)

    if not classes:
        typer.echo("  skip    db/__init__.py (no generated classes found)")
        return

    db_init = Path("db/__init__.py")
    db_init.write_text(_generate_db_init(classes), encoding="utf-8")
    typer.echo(f"  create  {db_init}")


@app.command()
def generate() -> None:
    """Generate Python client from SQL queries using SQLC."""
    _load_config()
    run(["sqlc", "generate"])
    _write_db_init()


@app.command()
def up() -> None:
    """Apply schema migration and generate Python client."""
    _, pg_env = _load_config()
    run(["pgschema", "apply", "--file", str(SCHEMA_PATH)], env=pg_env)
    run(["sqlc", "generate"])
    _write_db_init()


@app.command()
def studio() -> None:
    """Introspect database and launch Prisma Studio."""
    _load_config()
    run(["prisma", "db", "pull"])
    run(["prisma", "studio"])


@app.command()
def sql() -> None:
    """Launch Harlequin SQL IDE connected to the database."""
    config, _ = _load_config()
    run(["harlequin", config.database_url])


@app.command()
def diff() -> None:
    """Show what pgschema would change (human-readable)."""
    _, pg_env = _load_config()
    run(["pgschema", "plan", "--file", str(SCHEMA_PATH)], env=pg_env)
